### ISSUE TITLE
Error for incorrect password

### ISSUE THREAD

**Issue by baeolophus** [etag/portal_nuxt#12]
Right now interface just sits there, no feedback to user.

**Comment by tdpearson** [comment]
This is addressed in [test commit](https://github.com/etag/portal_nuxt/commit/67b7f42940496668a7f3ec25483fa58f2f30b0bf)

**Comment by baeolophus** [comment]
@tdpearson so we should close this issue?  I tested it on production and did get the error (although it was a soothing light blue - can I go change the color somewhere?)
