### ISSUE TITLE
Can't access any upload pages

### ISSUE THREAD

**Issue by baeolophus** [etag/portal_nuxt#18]
Eroma tested on the dev instance and clicking Reader Data, RFID Reads, and Tagged Data stays on the Antenna Design page.

**Comment by tdpearson** [comment]
Please include browser details and any error messages. This information is needed to be able to troubleshoot.

**Comment by baeolophus** [comment]
Looking back at her comments I believe it was Chrome btw.

**Comment by tdpearson** [comment]
I have pushed changes to the test instance and notified Eroma to try again.

**Comment by tdpearson** [comment]
Eroma confirmed that pages are loading. I am closing this issue as resolved.
