### ISSUE TITLE
Need error messages for upload

### ISSUE THREAD

**Issue by baeolophus** [etag/portal_nuxt#28]
Most workshop attendees had issues formatting data and going to API was very confusing.  Even having API error message appear by itself as a popup or on screen would help instead of them manually going to API.

**Comment by tdpearson** [comment]
I agree. Going to look at the task history under /api is a last resort and should not be the normal workflow.

**Comment by baeolophus** [comment]
I agree this should be one of the biggest "new" functionality priorities even above the date format (Since that can be worked R or other tools instead of Excel).
